### PR TITLE
Move to Typescript

### PR DESCRIPTION
**Pull request by rtfpessoa**
Based on #47

### CODE REVIEW

**Comment by rtfpessoa** [comment]
@whyboris I did some changes to have everything in TS with Jest.
What do you think?

**Comment by whyboris** [comment]
Beautiful! I pulled in this branch, installed the new dependencies, ran `npm test` and saw _Jest_ do its thing 💯 

Thank you for finalizing what I started 🙇 

Cheers 🙌

**Review by whyboris — APPROVED** [review]
Ship it 🚀 😁

**Comment by whyboris** [comment]
Will close #46

**Comment by whyboris** [comment]
By the way, just so you know -- I have an alias on my machine
```
alias diff='diff2html -s side --ig package-lock.json'
```
Which I run every time before I create a commit - to see just what I'm about to commit 👍 

Thank you again for your superbly-useful CLI 🙇

**Comment by rtfpessoa** [comment]
I did some more touches to enforce even more types.
Now I think I have a good idea of what is needed to do in the diff2html base.

@whyboris thanks a lot for your initial work and help to make this possible.

**Comment by rtfpessoa** [comment]
Released as version `4.0.0`

**Pull request merged**
