### PR TITLE
TypeScript implementation

### PR DESCRIPTION
**Pull request by whyboris**
This is a sample start on what a _TypeScript_ implementation would look like.

Discussion: https://github.com/rtfpessoa/diff2html-cli/issues/46

The key benefit of _TypeScript_ here is strict typing of method arguments. 

Other changes:
- using [`opn`](https://github.com/sindresorhus/opn) instead of `open` ([deprecated](https://github.com/jjrdn/node-open))
- simpler export
- minor version bumps

⚠️ THIS IS NOT READY TO MERGE ⚠️ 

If TypeScript were to be implemented, the release procedures would need to change somewhat (it's the _built_ files that need to be a part of the CLI, not the original _TypeScript_ files).

If idea is approved, before release I would:
- add [_JSDoc_](http://usejsdoc.org/) 
- add more strong typing of variables
- clean up `scripts` (e.g. `yarn test` would run `yarn build` first)
- figure out how to make the exported package still work 😅

### CODE REVIEW

**Comment by rtfpessoa** [comment]
@whyboris looks good. I need to get some time to test it.

**Comment by whyboris** [comment]
No rush -- and I'm happy to work more on this -- let me know if you have any recommended direction (especially if different than what I've done) 👍

**Comment by rtfpessoa** [comment]
@whyboris noticed some changes required:
* Change the main in package.json to the built one
* Change src from the published libraries to built

and overall I would prefer to move all files to TS and enable a couple more settings in the end to enforce types and best practices.

**Comment by rtfpessoa** [comment]
@whyboris noticed some changes required:
* Change the main in package.json to the built one
* Change src from the published libraries to built
* Change the binary inside bin to point to built directory also

and overall I would prefer to move all files to TS and enable a couple more settings in the end to enforce types and best practices.

**Comment by whyboris** [comment]
Sorry I dropped out after I opened this PR 😅 was a bit busy 😄 
I'll likely find some time in the next month to address your recommendations 👍

**Comment by rtfpessoa** [comment]
Closing for #53

**Pull request closed without merging**
