### PR TITLE
Ignore files command line flag

### PR DESCRIPTION
**Pull request by whyboris**
This PR allows users to specify particular files they would like to exclude from the diff output. E.g.

`diff2html-cli -ig true -- package-lock.json`

This is particularly useful when a file will cause severe delays before displaying and pollute the diff view (as is the case with a large `package-lock.json` or `yarn.lock` file).

For discussion, see https://github.com/rtfpessoa/diff2html-cli/issues/36

This is not a very clean bit of code to filter out files, but it works before the _diff_ is generated, speeding up the diff generation. 

An unfortunate artifact of this code is no other git commands can be passed in other than a list of files to exclude from the diff.

I am very happy to refactor the code if @rtfpessoa has recommendations 🙇

### CODE REVIEW

**Comment by rtfpessoa** [comment]
Hi @whyboris this is an interesting feature, but I would prefer if we used something less hackish.

For example: by using https://github.com/yargs/yargs/blob/HEAD/docs/tricks.md#arrays we could pass the files to ignore and then not mess with the remaining git args.

Does this make sense?

**Comment by whyboris** [comment]
Thank you for the reference! I just hadn't found the relevant documentation when I was crafting the PR.

I think I solved the problem better this time (see the commit below) 👍

**Review by rtfpessoa — APPROVED** [review]
LGTM

**Comment by rtfpessoa** [comment]
Released as https://github.com/rtfpessoa/diff2html-cli/tree/v2.7.0

**Pull request merged**
