### PR TITLE
escape $ (Fix issue #161)

### PR DESCRIPTION
**Pull request by xqin**
https://github.com/rtfpessoa/diff2html/issues/161

### CODE REVIEW

**Comment by rtfpessoa** [comment]
Hi @xqin thanks for the contribution.
Why would this be needed? I would like to understand the reason before going for a fix.

**Comment by xqin** [comment]
@rtfpessoa   detail  https://github.com/rtfpessoa/diff2html/issues/161

**Comment by xqin** [comment]
```bash
$ git diff
diff --git a/1.js b/1.js
index 587be6b..9ebead4 100644
--- a/1.js
+++ b/1.js
@@ -1 +1 @@
-x
+/$/

$ diff2html
```

before fix:
image


after fix:
image

is that clear? @rtfpessoa 

i'm from china, sorry for my english.

**Comment by rtfpessoa** [comment]
I would like to understand why you need to change that, to know if more chars are needed or if a better  fix could be achieved.

**Comment by hstarorg** [comment]
@rtfpessoa This pr means: if the diff file content include the `/$/` characters, the `diff2html-cli` will convert it as `/#x2F` for show in html. In fact, we expect it can show as `/$/`, keep the original value.

**Comment by xqin** [comment]
```
$ npm install -g diff2html-cli
$ git clone https://github.com/xqin/diff2html-cli-161.git
$ cd diff2html-cli-161
$ cat 1.js
$ diff2html d40bc9083 c1a2700ea59
```

you will see the diff.html result is not correct.

my code is 
```
console.log(/o$/.test('hello'))
console.log(/\$</.test('world'))
```
and the html result is
image


do you understand now?

**Comment by rtfpessoa** [comment]
I understand what it changes, but I would like to do a better fix than replacing $ manually, seems like a fast hack and not a proper solution. Does this make more sense?

**Comment by hstarorg** [comment]
Fix quickly is better than think a perfect solution, it's now affect function.

**Comment by rtfpessoa** [comment]
For multiple reasons like, this being a very small problem, you are the only person afected atm and since it can be fixed on your side, I would prefer to have a nice fix before deploying.

**Comment by xqin** [comment]
`seems like a fast hack and not a proper solution`.

NO!!! it's not a hack, it's a right solution.

AND

it's not only me can trigger this problem/bug, it's only me report this problem/bug.

https://github.com/search?q=replace+trim+language%3Ajavascript&type=Code&utf8=%E2%9C%93

```
function trim(s) {
  return s.replace(/^\s+/, '').replace(/\s+$/, '');
}
```

---


when the line content include following character, it will trigger this problem/bug.
```
$&
$<
$>
$"
$'
$/
```

because `diff2html` escape `&<>"'/` character into `&xxxx;` 
https://github.com/rtfpessoa/diff2html/blob/master/src/utils.js#L16-L21
this step is correct.

but `diff2html-cli` use replace method to make final html document, and the content has `$&xxx;`
https://github.com/rtfpessoa/diff2html-cli/blob/master/src/cli.js#L118
https://github.com/rtfpessoa/diff2html-cli/blob/master/dist/template.html#L36
image


`$&` in the content is [`lastMatch`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastMatch) of the regexp.
 
example:

```
let template = 'hello <!-- diff2html --> world'
let content = "console.log(/o$/.test('hello'))"

content = content.replace(/\//g, '&#x2f;') // diff2html escape
console.log(content) // "console.log(&#x2f;o$&#x2f;.test('hello'))"

let html = template.replace('<!-- diff2html -->', content) // diff2html-cli  _prepareHTML
console.log(html) // "hello console.log(&#x2f;o<!-- diff2html -->#x2f;.test('hello')) world"

```

**Comment by xqin** [comment]
fixed in https://github.com/rtfpessoa/diff2html-cli/commit/7e4dc7b890a74c627c11219b3257a59f63ef8467

**Pull request closed without merging**
