### PR TITLE
make sure git diff doesn't print out with colors

### LINKED ISSUE #30: something seems to be broken when using git HEAD^
when I try to run `diff2html HEAD^`
it opens the web browser and says it found 0 changes

when I try to run `pretty-diff HEAD^`
it shows me the correct diff

Not sure what's wrong but seems like something is broken

Platform: MacBook Pro (Retina, 15-inch, Mid 2014) macOS Sierra 10.12.6

### PR DESCRIPTION
**Pull request by thatkookooguy**
resolves #30

### CODE REVIEW

**Comment by rtfpessoa** [comment]
That case only works for the default `diff2html`, if you define something after `--` it will not pass the option.
 You need to check the first if case. Might be nice to check if the args passed already include it and if not add it.

**Comment by thatkookooguy** [comment]
tested locally (by installing with `npm install -g https://github.com/Thatkookooguy/diff2html-cli.git#patch-1`). 
But you know this code better than me. So you might want to check edge cases that I didn't think about :-)

**Comment by rtfpessoa** [comment]
Sorry for the delay. LGTM 👍

**Comment by rtfpessoa** [comment]
Released as 2.5.4

**Pull request merged**
